import math
numero = int(input("Ingrese un número: "))
seno = math.sin(numero)
coseno = math.cos(numero)
tangente = math.tan(numero)
raiz = math.sqrt(numero)
logaritmo_natural = math.log(numero)
logaritmo_base10 = math.log10(numero)
print("Del número:", numero)
print("Su seno es:", seno)
print("Su coseno es:", coseno)
print("Su tangente es:", tangente)
print("Su raíz cuadrada es:", raiz)
print("Su logaritmo natural es:", logaritmo_natural)
print("Su logaritmo en base 10 es:", logaritmo_base10)
